$HELP_MSG = "\e[1m\e[4mUsage: aoc <COMMAND> [ARGS]\e[0m:
\e[1m\e[4mCommon Commands\e[0m:
  \e[1m\e[4mr\e[0m\e[1mun\e[0m       [year] [day] [part]   Runs the solution on an input.
  \e[1m\e[4mi\e[0m\e[1mnit\e[0m      [year] [day] [lang]   Gets the input for a problem, makes solution files, and opens a workspace.
  \e[1m\e[4ms\e[0m\e[1mubmit\e[0m    [year] [day] [ans]    Submits the specified answer, or runs the solution and submits the output.
  \e[1m\e[4mt\e[0m\e[1mest\e[0m      [year] [day] [part]   Same as `run` but uses 'test_input.txt' as the input.

\e[1m\e[4mSetup Commands\e[0m:
  \e[1mcreate-year\e[0m  <year> <dir_name>  Creates a year directory.
  \e[1mmaster-init\e[0m                     Initializes the master directory.
  \e[1minfo-dump\e[0m                       Prints a bunch of trouble-shooting info.
  \e[1mconfig-gen\e[0m                      Print an example config file.

Commands are smart. You don't have to enter all arguments, or even in the right order.
Commands will do the most obvious(TM) thing if there are missing/weird parameters."

$TAMPER_WARNING = "# THIS FILE WAS AUTO-GENERATED BY GARNET-AOC. DO NOT MANUALLY MODIFY UNLESS YOU KNOW WHAT YOU ARE DOING"

$LANG_MAP = {
  'c' => 'c',
  'cpp' => 'cpp',
  'c++' => 'cpp',
  'py' => 'py',
  'python' => 'py',
  'rb' => 'rb',
  'ruby' => 'rb',
  'js' => 'js',
  'javascript' => 'js',
  'ts' => 'ts',
  'typescript' => 'ts',
  'pl' => 'pl',
  'perl' => 'pl',
  'elixir' => 'exs',
  'exs' => 'exs',
  'elixirscript' => 'exs',
  'hs' => 'hs',
  'haskell' => 'hs',
  'java' => 'java',
  'go' => 'go',
  'rs' => 'rs',
  'rust' => 'rs'
}

# if nil, is interpreted.
$COMPILER_MAP = {
  'java' => 'javac -d %%BIN_DIR%%',
  'c' => 'gcc -o %%BIN_DIR%%/p%%PART%%.out',
  'cpp' => 'g++ -o %%BIN_DIR%%/p%%PART%%.out',
  'rs' => 'rustc -o %%BIN_DIR%%/p%%PART%%.out'
}
$LIB_FILES = []

$INTERPRETER_MAP = {
  'rb' => 'ruby',
  'py' => 'python',
  'js' => 'node',
  'ts' => 'deno',
  'pl' => 'perl',
  'hs' => 'runhaskell',
  'go' => 'go run',
  'exs' => 'elixer',

  'java' => 'java',
  'c' => '',
  'cpp' => '',
  'rs' => ''
}

# if nil, use solution_file
$RUN_FILE_MAP = {
  'java' => '%%BIN_DIR%%/%%SOLUTION_FILE_NAME%%',
  'c' => '%%BIN_DIR%%/p%%PART%%.out',
  'cpp' => '%%BIN_DIR%%/p%%PART%%.out',
  'rs' => '%%BIN_DIR%%/p%%PART%%.out',
}

$SOLUTION_FILE_PREFIX = 'p'

$DEFAULT_LANG = 'python'

$IDE = 'nvim'

$SESSION = ''

$USE_ENV_INPUT = true

$USE_STDIN_INPUT = true

$MASTER_DIR = '/home/qy/dev/aoc'

$INPUTS_WITH_SOLUTIONS = false

# TODO add windos support :(
$CONFIG_DIR = '/home/qy/.config/aoc'
$CONFIG_DIR = File.expand_path($CONFIG_DIR)

require '~/.config/aoc/config'

$MASTER_DIR = File.expand_path($MASTER_DIR)
